// @ts-expect-error generated by default-sitemap module
import urls from '#default-sitemap/urls.mjs';

export default defineEventHandler((event) => {
	const config = useRuntimeConfig();

	const configuredSiteUrl = String(config.public.siteDomain ?? '').replace(
		/\/$/,
		'',
	);
	const siteUrl = configuredSiteUrl || getRequestURL(event).origin;

	setResponseHeader(event, 'content-type', 'application/xml; charset=utf-8');

	return createSitemapXml(siteUrl, urls);
});

function createSitemapXml(siteUrl: string, urls: string[]): string {
	const body = urls
		.map((path) => {
			const loc = escapeXml(`${siteUrl}${path}`);

			return `<url><loc>${loc}</loc></url>`;
		})
		.join('');

	return (
		'<?xml version="1.0" encoding="UTF-8"?>' +
		'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
		body +
		'</urlset>'
	);
}

function escapeXml(value: string): string {
	return value
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&apos;');
}
